# Generated by Django 4.2.7 on 2024-09-27 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_calculation_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 22, 8, 47, 971048, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
