# Generated by Django 4.2.7 on 2024-11-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronautflight',
            name='value',
            field=models.BooleanField(default=0, verbose_name='Поле м-м'),
        ),
    ]
